name: Testing Policies using Kyverno CLI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  kyverno_policy_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout respository
        uses: actions/checkout@v4.1.1

      - name: Setup Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.11.1'

      - name: Verify Kyverno CLI installation
        run: kyverno version

      - name: Test the policy against the resource
        run: kyverno apply policies/cpol-disallow-default-namespace.yml --resource manifests/bad_pod.yml --table
        continue-on-error: true

      - name: Get Output
        id: get_output
        run: |
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          exit "$exitcode"
